name: Init Full Translation

on:
  workflow_dispatch:  # 手动触发初始化

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Translate all .md files from docs/
        run: python .github/scripts/translate_all.py

      - name: Commit translated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Initial translation of all docs to English" || echo "Nothing to commit"
          git push
