name: Translate Using googletrans

on:
  workflow_dispatch:  # 手动触发

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install googletrans
        run: pip install googletrans==4.0.0-rc1

      - name: Run translation script
        run: python .github/scripts/translate_all_googletrans.py

      - name: Commit translated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Translated with googletrans" || echo "Nothing to commit"
          git push
